spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loja_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml
    contexts:
    default-schema: public
    drop-first: false
    database-change-log-table: databasechangelog
    database-change-log-lock-table: databasechangeloglock

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    enable:
      all: true
    prometheus:

